# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-12 12:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Elekto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enhavo', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Propono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=128)),
                ('enhavo', models.TextField()),
                ('pub_dato', models.DateTimeField(verbose_name='publikiĝdato')),
                ('fin_dato', models.DateTimeField(verbose_name='findato')),
                ('tipo', models.CharField(choices=[('normala_sekreta', 'Normala sekreta'), ('normala_publika', 'Normala publika'), ('elekto_estraro', 'Elekto de estraro'), ('elekto_komitatano_c', 'Elekto de komitatano C'), ('estraro_sekreta', 'Nur sekreta, por la estraro'), ('estraro_publika', 'Nur publika, por la estraro')], max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Vocxdono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dato', models.DateTimeField(verbose_name='dato de la voĉdono')),
                ('uzanto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vocxo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocxdonado.Elekto')),
            ],
        ),
        migrations.AddField(
            model_name='elekto',
            name='ligita_propono',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocxdonado.Propono'),
        ),
    ]
