# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocxdonado', '0002_auto_20180212_1237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vocxdono',
            options={'verbose_name_plural': 'voĉdonoj'},
        ),
        migrations.AddField(
            model_name='propono',
            name='nombro_eblaj_elektoj',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='nombro da eblaj elektoj'),
        ),
    ]
