# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-02 08:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocxdonado', '0004_auto_20180501_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propono',
            name='nombro_eblaj_elektoj',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(2)], verbose_name='nombro da eblaj elektoj'),
        ),
    ]
